# Generated by Django 4.1.7 on 2023-03-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='bolim nomi')),
                ('rasm', models.FileField(upload_to='bolimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='mahsulot nomi')),
                ('narx', models.FloatField()),
                ('brend', models.CharField(max_length=50)),
                ('davlat', models.CharField(max_length=50)),
                ('kafolat', models.CharField(max_length=100)),
                ('min_miqdor', models.IntegerField(default=2)),
                ('tasqilangan', models.BooleanField(default=True)),
                ('yetkazish', models.CharField(max_length=50)),
                ('mavjud', models.BooleanField(default=True)),
                ('chegirma', models.PositiveSmallIntegerField()),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assos_app.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Madia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasim', models.FileField(upload_to='madia')),
                ('masulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assos_app.mahsulot')),
            ],
        ),
    ]
