# Generated by Django 4.1.6 on 2023-03-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('assos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.PositiveSmallIntegerField()),
                ('matn', models.CharField(max_length=50)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assos_app.mahsulot')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profil')),
            ],
        ),
    ]
