# Generated by Django 4.1.6 on 2023-03-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('assos_app', '0002_izoh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanlagan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.SmallIntegerField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assos_app.mahsulot')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assos_app.mahsulot')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.profil')),
            ],
        ),
    ]
