# Generated by Django 4.1.6 on 2023-03-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('buyurtma_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savat',
            name='profil',
        ),
        migrations.AddField(
            model_name='savat',
            name='soni',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savat',
            name='umumiy',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.profil'),
        ),
        migrations.DeleteModel(
            name='Tanlagan',
        ),
    ]
